name = "Skate"
uuid = "d9f16b3c-1d8e-11eb-0a9c-5b1e7cfae1b2"
license = "MIT"
version = "0.1.0"
authors = ["Daniel A. Sprague"]
description = "Scalable, High Performance Bayesian Inference in Native Julia"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.123"
Enzyme = "0.13.129"
FiniteDifferences = "0.12.33"
ForwardDiff = "1.3.2"
LinearAlgebra = "1.12.0"
PositiveFactorizations = "0.2.4"
SpecialFunctions = "2.7.1"
Statistics = "1.11.1"
Test = "1.11.0"
