name = "Skate"
uuid = "d9f16b3c-1d8e-11eb-0a9c-5b1e7cfae1b2"
license = "MIT"
version = "0.2.0"
authors = ["Daniel A. Sprague"]
description = "Scalable, High Performance Bayesian Inference in Native Julia"

[deps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SkateBase = "a1b2c3d4-0001-4000-8000-000000000001"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Enzyme = "0.13.129"
Printf = "1.11.0"
Random = "1.11.0"
SpecialFunctions = "2.7.1"
Statistics = "1.11.1"
